/// Flutter icons ChickInEgg
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ChickInEgg
///      fonts:
///       - asset: fonts/ChickInEgg.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ChickInEgg {
  ChickInEgg._();

  static const _kFontFam = 'ChickInEgg';
  static const _kFontPkg = null;

  static const IconData chick_egg = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
